### ISSUE TITLE
Does not support api14

### ISSUE THREAD

**Issue by luck-fc** [ToDou/appbarlayout-spring-extension#1]
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.github.todou:appbarspring:1.0.1] aar\com.github.todou\appbarspring\1.0.1\AndroidManifest.xml

**Comment by ToDou** [comment]
试下1.0.2,我更新了下
当时主要是为了加那个RealtimeBlurView,所以把min设置为15的。
也可以直接覆盖<uses-sdk tools:overrideLibrary="......"/>
