### ISSUE TITLE
你好，关于NestedFixFlingScrollView的问题

### ISSUE THREAD

**Issue by httplzc** [ToDou/appbarlayout-spring-extension#16]
可以告知我NestedFixFlingScrollView和原版NestedScrollView修改了哪些内容吗》，我看两个类基本一致，没看到具体哪里有修改，我希望按照NestedFixFlingScrollView的编写思路，完成一个NestedFixFlingWebView的编写。谢谢。

**Comment by ToDou** [comment]
https://github.com/ToDou/appbarlayout-spring-behavior/blob/602d90bf7369393bc9c288dcf87e5303e14ae7b3/appbarspring/src/main/java/android/support/design/widget/NestedFixFlingScrollView.java#L44

改的地方很少，主要是NestedScrollView把这里check住了，没有走fling这个操作。
