### ISSUE TITLE
Missing tag for 1.0.3 version in Github repository

### ISSUE THREAD

**Issue by nerminator** [ToDou/appbarlayout-spring-extension#22]
We are using 1.0.3 version of Appbarspring library in one of our projects. 
For our legal policies, we have to see the License file for 1.0.3 version. 
1.0.3 version is not tagged in github repository. 
Could you please add a tag for 1.0.3 version?

**Comment by ToDou** [comment]
See Version 1.0.3. But I suggest to use the 1.0.5
