### ISSUE TITLE
android:allowBackup="true"

### ISSUE THREAD

**Issue by hurshi** [ToDou/appbarlayout-spring-extension#24]
remove android:allowBackup="true" ?

**Comment by ToDou** [comment]
[remove allowBackup true in library](https://github.com/ToDou/appbarlayout-spring-behavior/commit/8148bb1b52ec0284e50ff9d4b5159ab699e423d9)

**Comment by ToDou** [comment]
It's fixed [8148bb1](https://github.com/ToDou/appbarlayout-spring-behavior/commit/8148bb1b52ec0284e50ff9d4b5159ab699e423d9)
