### ISSUE TITLE
包名这样写是不是有种钦定的感觉

### ISSUE THREAD

**Issue by 29995270** [ToDou/appbarlayout-spring-extension#3]

**Comment by ToDou** [comment]
专门科普了下‘钦定的感觉‘意思==.
没办法最初实现这个其实是自己包名，再加很多类，design包里很多类基本都是同包下使用,所以为一两个方法，得拷贝出一连串的类。这样增加了类数量，一个库其实就那么点东西。只为简洁点，但愿design个别方法类可以早点开放出来。
