### ISSUE TITLE
28.0.0的有问题

### ISSUE THREAD

**Issue by NeVaDaAAA** [ToDou/appbarlayout-spring-extension#35]
我的项目support是28.0.0
会报如下错误
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/design/widget/ViewUtils;
问题排查的时候，将您的supportLibraryVersion = '27.1.1'修改为supportLibraryVersion = '28.0.0'
报如下错误
![image](https://user-images.githubusercontent.com/20659340/48532563-e0b15500-e8db-11e8-8ac5-80d69d6ecc4d.png)
![image](https://user-images.githubusercontent.com/20659340/48532576-e9099000-e8db-11e8-8e66-c7a8b8be1fb0.png)
一直在用您的这个库 非常棒 希望您能适配一下 十分感谢

**Comment by alfredzhang0728** [comment]
+1

**Comment by ToDou** [comment]
https://github.com/ToDou/appbarlayout-spring-behavior/tree/v1.0.9
