### ISSUE TITLE
supportLibraryVersion=28.0.0适配问题解决

### ISSUE THREAD

**Issue by yuxiangxin** [ToDou/appbarlayout-spring-extension#37]
android.support.design.widget.AppBarLayoutSpringBehavior#updateAppBarLayoutDrawableState(){
final boolean changed = layout.setCollapsedState(collapsed); -> final boolean changed = layout.setLiftedState(collapsed);
}

**Comment by ToDou** [comment]
https://github.com/ToDou/appbarlayout-spring-behavior/tree/v1.0.9
