### ISSUE TITLE
androidX 1.0.8 hint

### ISSUE THREAD

**Issue by mafanwei** [ToDou/appbarlayout-spring-extension#44]
The given artifact contains a string literal with a package reference 'android.support.design.widget' that cannot be safely rewritten. Libraries using reflection such as annotation processors need to be updated manually to add support for androidx.

[Processor] Library '/Users/apple/.gradle/caches/modules-2/files-2.1/com.github.todou/appbarspring/1.0.8/5e3b335df3d1a43f52d358545551409182bd4a99/appbarspring-1.0.8.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

**Comment by BackPackerDz** [comment]
Any solution?

**Comment by mafanwei** [comment]
I write this myself.
