### ISSUE TITLE
在AS的gradle中添加依赖后，一直提示error？

### ISSUE THREAD

**Issue by 452MJ** [ToDou/appbarlayout-spring-extension#5]
Error:Could not find com.android.support:appcompat-v7:24.2.1.
Required by:
    XXXX:app:unspecified
    XXXX:app:unspecified > com.github.todou:appbarspring:1.0.2

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

只有在添加该库依赖会出现这种情况，去掉就可以正常编译了。不知道什么原因？

**Comment by ToDou** [comment]
support包版本多少，是24.2.1么

**Comment by ToDou** [comment]
点Open Android SDK Manager 升级下
