### ISSUE TITLE
build.gradle error?

### ISSUE THREAD

**Issue by amanzan** [ToDou/appbarlayout-spring-extension#8]
I get this after cloning the repository and trying to build:

Error:(4, 0) Could not get unknown property 'compile_sdk_version' for object of type com.android.build.gradle.AppExtension.
<a href="openFile:/Users/alberto/Desktop/appbarlayout-spring-behavior/app/build.gradle">Open File</a>

**Comment by ToDou** [comment]
I am sorry!The file 'gradle.properties' didn't push to the master

**Comment by ToDou** [comment]
Have uploaded
!
